# User config
author: "Conor"
tagline: "You want stories, you got stories"
description: "Lots of example Stories"
keywords: "Stories"
email: "conor@conoroneill.com"
linkedin: "https://www.linkedin.com/in/conoroneill"
twitter: "https://twitter.com/conoro"
github: "https://github.com/conoro"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
